image: buildkite/puppeteer:latest

cache:
  paths:
    - node_modules/

make_pdf:
    except:
        - tags
    stage: build
    script:
        - apt-get update && apt-get install -y git
        - npm install
        - ./node_modules/.bin/asciidoctor-web-pdf -v -t --template-require ./base/template.js --require ./base/inline-code.js -S unsafe asciidoctor-cheat-sheet.adoc -o ./build/asciidoctor-cheat-sheet.pdf
    artifacts:
        paths:
            - build
        name: '${CI_PROJECT_DIR}_${CI_COMMIT_REF_NAME}'
        when: on_success
        expire_in: '1 week'
